name: Build & Upload APK

on:
  push:
    tags:
      - 'v4.3.3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Upgrade Gradle wrapper to 7.5
        run: ./gradlew wrapper --gradle-version 7.5

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Symphony-4.3.3-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
